
#
#	# delete containers
#	docker rm -f $(docker ps -aq)
#



#
#	docker network rm strings_1
# 	docker network create --subnet=192.168.0.0/24 strings_1
#

#version: '3'

services:
  jumps:
    image: jumps:v2.1.0
    container_name: Foam_Pet.1
    networks:
      strings_1:
        ipv4_address: 192.168.0.11
    volumes:
      - .:/Metro
    stdin_open: true
    tty: true
    privileged: true

networks:
  strings_1:
    external: true
