

[package]
name = "Octas_1"
version = "1.0.0"
authors = []

[addresses]
founder = "_"

[dev-addresses]


[dependencies.AptosFramework]
local = "/Metro/aptos-core/aptos-move/framework/aptos-framework" 

[dependencies.AptosStdlib]
local = "/Metro/aptos-core/aptos-move/framework/aptos-stdlib" 


